### ISSUE TITLE
Errors in VSCode

### ISSUE THREAD

**Issue by etaggus** [ryb73/ppx_decco#10]
When using VSCode, I'm seeing this error:

```
sh: 1: /path/to/project/lib/bs/native/ppx_decco.native: not found
File "", line 1:
Error: Error while running external preprocessor
Command line: /path/to/project/lib/bs/native/ppx_decco.native '/tmp/user/1006/camlppxd4f71d' '/tmp/user/1006/camlppx39ebce'
```

I'm on version `0.0.14`, and tested it with `bs-platform@5.0.4` and `bs-platform@5.0.2`.

The code compiles fine, but error hinting in VSCode is broken due to this.

**Comment by mrmurphy** [comment]
I'm seeing this as well. Command line compiler is fine, but VS Code has this error. I'm using `bs-platform@5.0.2`.

**Comment by ryb73** [comment]
@ohana54 mentions a workaround in jaredly/reason-language-server#278. I've update the README to include this fix.

**Comment by mrmurphy** [comment]
Thank you!
