### ISSUE TITLE
This project is amazing !

### ISSUE THREAD

**Issue by thangngoc89** [ryb73/ppx_decco#18]
I just want to say thank you  @ryb73 . Your project is amazing and it removes all the boilerplate that comes with decoding / encoding.

Furthermore, this ppx is compatible with [ppx_jsobject_conv](https://github.com/little-arhat/ppx_jsobject_conv) and oh boy. Communicating between js_of_ocaml and bucklescript can't be easier. Using the same `Types.re` on both side with different deriving tag and bam. 

It works !
So once again, thank you very much

**Comment by ryb73** [comment]
Thanks for the kind words @thangngoc89! Glad it's working well for you!
