### ISSUE TITLE
Support recursive types

### ISSUE THREAD

**Issue by ryb73** [ryb73/ppx_decco#6]
e.g.
```reason
type t = A | B(t);

type r1 = W | X(r2)
and r2 = Y | Z(r1);
```

**Comment by boyswan** [comment]
I'd be happy to (try) to take a look

**Comment by ryb73** [comment]
Thanks @boyswan! It may be as easy as making [this line](https://github.com/ryb73/ppx_decco/blob/master/ppx/bin/Structure.re#L34), where the `let` statements are generated, use `Recursive` instead of `Nonrecursive`. Unfortunately I can't find the documentation I used when developing this originally, but these might help:
https://docs.mirage.io/ocaml-migrate-parsetree/Ast_402/index.html
https://github.com/ocaml-ppx/ocaml-migrate-parsetree/blob/master/src/ast_402.ml

One of the tricky things will be that, IIRC, the compiler will emit a warning if the `rec` flag is included but recursion isn't used, so we won't want to include it for *all* codecs – just the ones we generate for types that are actually recursive.

As far as environment setup and building goes, the package.json and .travis.yml will point you in the right direction. Let me know if it's not intuitive to get up and running and I can put together a guide.

Finally, you can run `ppx/_esy/default/build/install/default/lib/ppx_decco/ppx.exe in.ml > out.ml` to see what the output of the PPX is given an Ocaml input. AFAIK the ppx can't be run directly on a Reason file, but you can use `refmt` to convert between `re` and `ml`.

Let me know what questions you have!

**Comment by ryb73** [comment]
So I started looking into this and ran into a snag: the `rec_flag` for type declarations isn't exposed in Ast_402. This means that we can't detect the `nonrec` flag which is necessary to do this properly. This may need to wait until #23 is done.
