### ISSUE TITLE
`Decco.decodeError` type forces decco to be a runtime dependency

### ISSUE THREAD

**Issue by yawaramin** [ryb73/ppx_decco#7]
If we don't use `Decco.decodeError`, we can keep decco as a devDep. But referring to that type forces it to be a runtime dep. We might be able to get around this by making `decodeError` a `Js.t` type, like `{. "path": string, "message": string, "value": Js.Json.t}`. A structural type like this would be effectively 'detached' from any module.

**Comment by ryb73** [comment]
IIRC, the PPX generates code which references the `Decco` module, so decco would be needed as a bs-dependency regardless. e.g. [this](https://github.com/ryb73/ppx_decco/blob/master/ppx/bin/Codecs.re#L34) is where encoders/decoders for primitive types are generated. Notice that they use Decco.stringToJson, Decco.stringFromJson, etc.

I've updated the README to clarify this.
