### ISSUE TITLE
Exponentially increasing compile times for large records.

### ISSUE THREAD

**Issue by nireno** [ryb73/ppx_decco#8]
Adding decco to one of my larger records causes compile times of 10+ seconds. You can try to reproduce it by building this [modified test](https://github.com/nireno/ppx_decco/commit/4ae192276b4ee525c59c8337a3cb3ab7f27f10d0) where I simply added a huge record.

```
[@decco]
type massiveRecord = {
  x1: int,
  x2: int,
  x4: int,
  x5: int,
  x6: int,
  x7: int,
  x8: int,
  x9: int,
  x10: int,
  x11: int,
  x12: int,
  x13: int,
  x14: int,
  x15: int,
  x16: int,
  x17: int,
  x18: int,
  x19: int,
  x20: int,
  x21: int,
  x22: int,
  x23: int,
  x24: int,
  x25: int,
};
```
Compiling this takes about 12s on my machine.
Each field I add seems to almost double the compile time.

**Comment by ryb73** [comment]
Good catch! This should be fixed in #9
